version: '3.8'

services:
  yads-test:
    build: .
    container_name: yads-test-container
    hostname: yads-test
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp/yads-test:/tmp
    ports:
      - "8080:8080"    # VS Code Server
      - "80:80"        # Web server
      - "443:443"      # HTTPS
      - "3306:3306"    # MySQL
      - "5432:5432"    # PostgreSQL
      - "6379:6379"    # Redis
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=UTC
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: /home/yadsuser/entrypoint.sh
