name: Auto Version Bump

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'version'
      - 'bump-version.sh'
      - 'MANUAL-UNINSTALL.md'
      - 'manual-uninstall.sh'
      - 'fix-*.sh'
      - 'test-*.sh'
      - '.github/workflows/version-bump.yml'

jobs:
  auto-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get current version
      id: current-version
      run: |
        # Get the latest tag
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        current_version="${latest_tag#v}"
        echo "current=$current_version" >> $GITHUB_OUTPUT
        echo "Current version: $current_version"
    
    - name: Bump patch version
      id: bump-version
      run: |
        current="${{ steps.current-version.outputs.current }}"
        
        # Split version into parts
        IFS='.' read -r major minor patch <<< "$current"
        
        # Bump patch version
        patch=$((patch + 1))
        new_version="$major.$minor.$patch"
        
        echo "new=$new_version" >> $GITHUB_OUTPUT
        echo "New version: $new_version"
    
    - name: Update version file
      run: |
        new_version="${{ steps.bump-version.outputs.new }}"
        echo "$new_version" > version
        echo "Updated version file to: $new_version"
    
    - name: Update yads script version
      run: |
        new_version="${{ steps.bump-version.outputs.new }}"
        
        # Update default version in get_version function
        sed -i "s/echo \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/echo \"$new_version\"/" yads
        
        # Update upgrade function version
        sed -i "s/echo \"[0-9]\+\.[0-9]\+\.[0-9]\+\" > \"\$HOME\/.local\/bin\/version\"/echo \"$new_version\" > \"\$HOME\/.local\/bin\/version\"/" yads
        
        echo "Updated yads script to version: $new_version"
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add version yads
        git commit -m "Auto-bump version to v${{ steps.bump-version.outputs.new }}" || echo "No changes to commit"
    
    - name: Create and push tag
      run: |
        new_version="${{ steps.bump-version.outputs.new }}"
        
        # Create tag
        git tag -a "v$new_version" -m "Release v$new_version"
        
        # Push changes and tag
        git push origin master
        git push origin "v$new_version"
        
        echo "Created and pushed tag: v$new_version"
