name: Test YADS Syntax

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Manual trigger

jobs:
  test-syntax:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test script syntax
      run: |
        echo "Testing YADS script syntax..."
        
        # Test main script
        if ! bash -n yads; then
          echo "❌ ERROR: yads script has syntax errors"
          exit 1
        fi
        echo "✅ yads script syntax is correct"
        
        # Test install script
        if ! bash -n install.sh; then
          echo "❌ ERROR: install.sh script has syntax errors"
          exit 1
        fi
        echo "✅ install.sh script syntax is correct"
        
        # Test modules
        for module in modules/*.sh; do
          if [[ -f "$module" ]]; then
            if ! bash -n "$module"; then
              echo "❌ ERROR: $module has syntax errors"
              exit 1
            fi
            echo "✅ $module syntax is correct"
          fi
        done
    
    - name: Test line endings
      run: |
        echo "Testing line endings..."
        
        # Check for CRLF line endings
        if file yads | grep -q "CRLF"; then
          echo "❌ ERROR: yads script has CRLF line endings"
          echo "Run: tr -d '\r' < yads > yads.tmp && mv yads.tmp yads"
          exit 1
        fi
        echo "✅ yads script has correct line endings"
        
        # Check other scripts
        for script in install.sh modules/*.sh; do
          if [[ -f "$script" ]]; then
            if file "$script" | grep -q "CRLF"; then
              echo "❌ ERROR: $script has CRLF line endings"
              exit 1
            fi
            echo "✅ $script has correct line endings"
          fi
        done
    
    - name: Test module loading
      run: |
        echo "Testing module loading..."
        
        # Test if modules can be sourced
        for module in modules/*.sh; do
          if [[ -f "$module" ]]; then
            if ! bash -c "source $module" 2>/dev/null; then
              echo "❌ ERROR: $module cannot be sourced"
              exit 1
            fi
            echo "✅ $module loads correctly"
          fi
        done
    
    - name: Test command structure
      run: |
        echo "Testing command structure..."
        
        # Test if yads script has proper command handling
        if ! grep -q "case.*\${1:-help}" yads; then
          echo "❌ ERROR: yads script missing proper command handling"
          exit 1
        fi
        echo "✅ yads script has proper command structure"
        
        # Test if version command exists
        if ! grep -q "version.*--version.*-v" yads; then
          echo "❌ ERROR: yads script missing version command"
          exit 1
        fi
        echo "✅ yads script has version command"
        
        # Test if help command exists
        if ! grep -q "help.*--help.*-h" yads; then
          echo "❌ ERROR: yads script missing help command"
          exit 1
        fi
        echo "✅ yads script has help command"
    
    - name: Test file permissions
      run: |
        echo "Testing file permissions..."
        
        # Check if scripts are executable
        if [[ ! -x yads ]]; then
          echo "❌ ERROR: yads script is not executable"
          exit 1
        fi
        echo "✅ yads script is executable"
        
        if [[ ! -x install.sh ]]; then
          echo "❌ ERROR: install.sh script is not executable"
          exit 1
        fi
        echo "✅ install.sh script is executable"
    
    - name: Test Git attributes
      run: |
        echo "Testing Git attributes..."
        
        # Check if .gitattributes exists
        if [[ ! -f ".gitattributes" ]]; then
          echo "❌ ERROR: .gitattributes file missing"
          exit 1
        fi
        echo "✅ .gitattributes file exists"
        
        # Check if line ending rules are defined
        if ! grep -q "eol=lf" .gitattributes; then
          echo "❌ ERROR: .gitattributes missing line ending rules"
          exit 1
        fi
        echo "✅ .gitattributes has line ending rules"
    
    - name: Generate syntax report
      run: |
        echo "=== YADS Syntax Test Report ==="
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Date: $(date)"
        echo
        echo "✅ All syntax tests passed!"
        echo
        echo "Test Summary:"
        echo "- Script syntax: ✅ PASS"
        echo "- Line endings: ✅ PASS"
        echo "- Module loading: ✅ PASS"
        echo "- Command structure: ✅ PASS"
        echo "- File permissions: ✅ PASS"
        echo "- Git attributes: ✅ PASS"
